### ISSUE TITLE
CSS Source

### ISSUE THREAD

**Issue by sdhunt** [krtong/Capstone#3]
The CSS Source code is well structured for the most part, though the formatting is inconsistent in places:
https://github.com/krtong/Capstone/blob/6c5e778a8896d42aed0d8501e072a8149ec45de4/resources/css/style.css#L133-L140

The generally accepted convention for formatting CSS is to put the closing brace of the rule body in column 1, and to include a single blank line between rule declarations. 

It is good that you have included comments to mark sections, but use more whitespace to accentuate the break:
https://github.com/krtong/Capstone/blob/6c5e778a8896d42aed0d8501e072a8149ec45de4/resources/css/style.css#L254-L258
```
        } 
} 

/* doesnt hurt to keep practicing */ 

#keep-practicing { 
    display: flex; 
```

**Comment by krtong** [comment]
this was an import issue to github. the spacing on atom doesnt have the inconsistencies. I'm guessing there was a couple tab spaces I missed
